### ISSUE TITLE
Extend and refactor communication interfaces

### ISSUE THREAD

**Issue by domire8** [aica-technology/network-interfaces#23]
This is something we've been talking about for a long time and I would like to tackle this sooner than later. We need to extend our network interfaces with other types of socket communications than just ZMQ (UDP, TCP, etc.). This is required for a lot of hardware interfaces.

This is a big project and it's hard to lay out a plan for each class already but I think it's better to start somewhere simple and build from that.

Note that I take some inspiration from ros-industrial.

```[tasklist]
### Tasks
- [ ]
- [ ] https://github.com/aica-technology/network-interfaces/issues/24
- [ ] https://github.com/aica-technology/network-interfaces/issues/26
- [ ] https://github.com/aica-technology/network-interfaces/issues/28
- [ ] https://github.com/aica-technology/network-interfaces/issues/30
- [ ] https://github.com/aica-technology/network-interfaces/issues/32
- [ ] https://github.com/aica-technology/network-interfaces/issues/35
- [ ] https://github.com/aica-technology/network-interfaces/issues/31
- [ ] https://github.com/aica-technology/network-interfaces/issues/46
```

**Comment by eeberhard** [comment]
Good work @domire8 ! 🚀

**Comment by domire8** [comment]
I will close this for now, but python bindings would be nice at some point
